#!/usr/bin/env bash

# Update the package lists
apt-get -y update

# Install nginx
apt-get -y install nginx

# Make sure nginx is running
# service nginx start

# Create a simple HTML page with "Hello World!:
echo "Hello World!" > /var/www/html/index.html

# Restart nginx (using the -y option to avoid prompts)
service nginx start
