#!/usr/bin/env bash
# Redirection

sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" | sudo dd status=none of=/var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
N_RED="\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

sudo cp /etc/nginx/sites-available/default{,.backup}
sudo sed -i "53i $N_RED" /etc/nginx/sites-available/default

N_RED="\n\terror_page 404 /404.html;\n\n\tlocation /404.html {\n\t\tinternal;\n\t}\n"
sudo sed -i "53i $N_RED" /etc/nginx/sites-available/default

# sudo sed -i '/^\server_name.*/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
