#!/usr/bin/env bash
# script to run nginx and listen to port 80
sudo apt-get update && sudo apt-get install -y nginx && service nginx start
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
service nginx restart
