#!/usr/bin/env bash
# script to run nginx and listen to port 80

# Install Nginx if not installed
sudo apt-get update
sudo apt-get install -y nginx
# Ensure Nginx is running
service nginx start
# Modifying Nginx configuration to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
