#!/usr/bin/env bash
# making a shorter nginx port 80 script
sudo apt-get update && sudo apt-get install -y nginx && service nginx start
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
service nginx restart && service nginx stop
