#!/bin/bash
# 101-manage_my_process init script

# Function to start manage_my_process
start_manage_my_process() {
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process started"
}

# Function to stop manage_my_process
stopped_manage_my_process() {
	if [ -f /var/run/my_process.pid ]; then
		pid=$(cat /var/run/my_process.pid)
		kill - TERM $pid
		rm -f /var/run/my_process.pid
		echo "manage_my_process stopped"
	else
		echo "manage_my_process is not running"
	fi
}

# Main script
case $1 in
	start)
		start_manage_my_process
		;;
	stop)
		stop_manage_my_process
		;;
	restart)
		stop_manage_my_process
		start_manage_my_process
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
