#!/usr/bin/env bash
# script to stop the '4-to_infinity_and_beyond' process without using kill or killall

# pkill -f 7-highlander

pid=$(pgrep -f "7-highlander")

if [[ -n "$pid" ]]; then
	# echo "Terminating 7-highlander process with PID $pid"
	pkill -f "7-highlander"
	sleep 2
	# pkill -P $pid
else
	echo "7-highlander process not found."
fi
