#!/usr/bin/env bash
# script to display numbers from 1 to 100 with FizzBuzz requirements

v=1
while [ $v -le 100 ]; do
	if ((v % 3 == 0)) && ((v % 5 == 0)); then
		echo -n "FizzBuzz"
	elif ((v % 3 == 0)); then
		echo -n "Fizz"
	elif ((v % 5 == 0)); then
		echo -n "Buzz"
	else
		echo -n "$v"
	fi

	if [ $v -ne 100 ]; then
		echo -n " "
	fi

	v=$((v + 1))
done
echo
