#!/usr/bin/env bash
# script that tells a story about the users in passwd file

while IFS=":" read -r username _ uid _ _ home shell; do
	echo "The user $username is part of the $uid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
