#!/usr/bin/env bash
# script that configures the container to run Nginx as the nginx user
# give conf permission
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/sites-enabled/default
sudo chmod 644 /etc/nginx/sites-enabled/default
ch_portconf="/etc/nginx/sites-enabled/default"
n_port=8080

# update nginx.conf
# sudo sed -Ei "s/\s*#?\s*user .*/user nginx;/" /etc/nginx/nginx.conf

if [ -f "$n_port" ]; then
	sudo sed -i "s/Listen 80/Listen $n_port/" $ch_portconf
	sudo service nginx restart
fi

if sudo service nginx status &> /dev/null; then
	sudo service nginx restart
fi
